import Mock, { mock } from 'mockjs'

let list = []
export default {
    getStateDate:()=>{
        for(let i=0; i<7;i++){
            list.push(
                Mock.mock({
                    苹果:Mock.Random.float(100,8000,0,0),
                    vivo:Mock.Random.float(100,8000,0,0),
                    OPPO:Mock.Random.float(100,8000,0,0),
                    华为:Mock.Random.float(100,8000,0,0),
                    三星:Mock.Random.float(100,8000,0,0),
                    小米:Mock.Random.float(100,8000,0,0)
                })
            )
        }
        return {
            code:20000,
            data:{
                videDate:[
                    {
                        name:'小米',
                        value:2999
                    },
                    {
                        name:'苹果',
                        value:2000
                    },
                    {
                        name:'vivo',
                        value:1699
                    },
                    {
                        name:'OPPO',
                        value:4999
                    },
                    {
                        name:'华为',
                        value:3699
                    },
                    {
                        name:'三星',
                        value:2499
                    }
                ],
                userDate:[
                    {
                        date:'周一',
                        new:5,
                        active:200
                    },
                    {
                        date:'周二',
                        new:5,
                        active:500
                    },
                    {
                        date:'周三',
                        new:20,
                        active:550
                    },
                    {
                        date:'周四',
                        new:66,
                        active:600
                    },
                    {
                        date:'周五',
                        new:20,
                        active:100
                    },
                    {
                        date:'周六',
                        new:65,
                        active:400
                    },
                    {
                        date:'周日',
                        new:10,
                        active:300
                    }
                ],
                orderDate:{
                    date:[],
                    data:List
                },
                tableData:[
                    {
                        name:'vivo',
                        todayBuy:200,
                        monthBuy:550,
                        totalBuy:22400
                    }
                ]
            }
        }
    }
}